# Generated by Django 6.0.1 on 2026-01-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('azbankgateways', '0005_alter_bank_bank_type_alter_bank_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_type',
            field=models.CharField(
                choices=[
                    ('BMI', 'BMI'),
                    ('SEP', 'SEP'),
                    ('ZARINPAL', 'Zarinpal'),
                    ('ZIBAL', 'Zibal'),
                    ('BAHAMTA', 'Bahamta'),
                    ('MELLAT', 'Mellat'),
                    ('IRANDARGAH', 'IranDargah'),
                    ('ASANPARDAKHT', 'AsanPardakht'),
                ],
                max_length=50,
                verbose_name='Bank',
            ),
        ),
    ]
